language: php

sudo: false

php:
  - 7.2

services:
  - mysql

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  - OS2WEB_PATH=$(pwd);

install:
  - mysql -e 'create database drupal;'
  - composer global require drush/drush:8.x-dev drupal/coder mglaman/drupal-check friendsoftwig/twigcs
  - export PATH="$HOME/.config/composer/vendor/bin:$PATH"
  - phpcs --config-set installed_paths ../../drupal/coder/coder_sniffer
  - echo 'sendmail_path = /bin/true' > $(php --ini|grep -m 1 "ini files in:"|cut -d ":" -f 2)/sendmail.ini
  - phpenv rehash
  - nvm install node
  - nvm use node
  - npm install --global yarn
  - cd ../ && drush dl drupal-8 --drupal-project-rename=drupal
  - cd drupal
  - DRUPAL_ROOT=$(pwd)
# See definition of variabled in Travis CI config.
#  - export REPOSITORIES='"repositories": \['
#  - export REPOSITORIES_REPLACE='"repositories": \[\{"type": "path","url": "..\/os2web", "options": \{"symlink": false\}\},\},'
#  - export REQUIRE='"require": {'
#  - export REQUIRE_REPLACE='"require": {"os2web\/os2web": "\*",'
  - sed -i "s/$REPOSITORIES/$REPOSITORIES_REPLACE/g" composer.json
  - sed -i "s/$REQUIRE/$REQUIRE_REPLACE/g" composer.json
  - composer update
  - cd $DRUPAL_ROOT/core
  - yarn install
  - npm install --global eslint-config-drupal-bundle stylelint

script:
  - cd $OS2WEB_PATH
  - phpcs --standard=Drupal --ignore=*.md ./
  - twigcs $OS2WEB_PATH
  - cd $DRUPAL_ROOT/core
  - eslint $DRUPAL_ROOT/modules/contrib/os2forms
  - stylelint --aei $DRUPAL_ROOT/modules/contrib/os2forms/**/*.css
  - drupal-check $DRUPAL_ROOT/profiles
  - cd $DRUPAL_ROOT
  - drush si os2web --db-url=mysql://root:@127.0.0.1/drupal --yes
