; This file was auto-generated by drush make
core = 7.x

api = 2
projects[] = "drupal"

; OS2Web Modules
projects[os2web][download][type] = "git"
projects[os2web][download][url] = ""
projects[os2web][type] = "profile"

projects[os2web_base][download][type] = "git"
projects[os2web_base][download][url] = "https://github.com/OS2web/os2web_base.git"
projects[os2web_base][type] = "module"
projects[os2web_base][subdir] = "os2web"

projects[os2web_borger_dk][download][type] = "git"
projects[os2web_borger_dk][download][url] = "https://github.com/OS2web/os2web_borger_dk.git"
projects[os2web_borger_dk][type] = "module"
projects[os2web_borger_dk][subdir] = "os2web"

projects[os2web_contact][download][type] = "git"
projects[os2web_contact][download][url] = "https://github.com/OS2web/os2web_contact.git"
projects[os2web_contact][type] = "module"
projects[os2web_contact][subdir] = "os2web"

projects[os2web_esdh_field][download][type] = "git"
projects[os2web_esdh_field][download][url] = "https://github.com/OS2WebCore/os2web_esdh_field.git"
projects[os2web_esdh_field][type] = "module"
projects[os2web_esdh_field][subdir] = "os2web"

projects[os2web_iframe_field][download][type] = "git"
projects[os2web_iframe_field][download][url] = "https://github.com/OS2web/os2web_iframe_field.git"
projects[os2web_iframe_field][type] = "module"
projects[os2web_iframe_field][subdir] = "os2web"

projects[os2web_search][download][type] = "git"
projects[os2web_search][download][url] = "https://github.com/OS2web/os2web_search.git"
projects[os2web_search][type] = "module"
projects[os2web_search][subdir] = "os2web"

projects[os2web_spotbox][download][type] = "git"
projects[os2web_spotbox][download][url] = "https://github.com/OS2web/os2web_spotbox.git"
projects[os2web_spotbox][type] = "module"
projects[os2web_spotbox][subdir] = "os2web"

projects[os2web_taxon_api][download][type] = "git"
projects[os2web_taxon_api][download][url] = "https://github.com/OS2web/os2web_taxon_api.git"
projects[os2web_taxon_api][type] = "module"
projects[os2web_taxon_api][subdir] = "os2web"

projects[os2web_taxon_taxonomy][download][type] = "git"
projects[os2web_taxon_taxonomy][download][url] = "https://github.com/OS2web/os2web_taxon_taxonomy.git"
projects[os2web_taxon_taxonomy][type] = "module"
projects[os2web_taxon_taxonomy][subdir] = "os2web"

projects[os2web_taxonomies][download][type] = "git"
projects[os2web_taxonomies][download][url] = "https://github.com/OS2web/os2web_taxonomies.git"
projects[os2web_taxonomies][type] = "module"
projects[os2web_taxonomies][subdir] = "os2web"

; Contrib modules
projects[views_bulk_operations][subdir] = "contrib"

projects[apachesolr][subdir] = "contrib"

projects[bigmenu][subdir] = "contrib"

projects[ctools][subdir] = "contrib"

projects[ckeditor][subdir] = "contrib"

projects[content_taxonomy][subdir] = "contrib"

projects[context][subdir] = "contrib"

projects[facetapi][subdir] = "contrib"

projects[date][subdir] = "contrib"

projects[delta][subdir] = "contrib"

projects[eim][subdir] = "contrib"

projects[entity][subdir] = "contrib"

projects[entityreference][subdir] = "contrib"

projects[expire][subdir] = "contrib"

projects[extlink][subdir] = "contrib"

projects[features][subdir] = "contrib"

projects[feeds][subdir] = "contrib"

projects[feeds_xpathparser][subdir] = "contrib"

projects[field_group][subdir] = "contrib"

projects[field_slideshow][subdir] = "contrib"

projects[fieldable_panels_panes][subdir] = "contrib"

projects[file_entity][subdir] = "contrib"

projects[globalredirect][subdir] = "contrib"

projects[honeypot][subdir] = "contrib"

projects[i18n][subdir] = "contrib"

projects[panels][subdir] = "contrib"

projects[image_url_formatter][subdir] = "contrib"

projects[imagefield_crop][subdir] = "contrib"

projects[job_scheduler][subdir] = "contrib"

projects[jquery_update][subdir] = "contrib"

projects[l10n_client][subdir] = "contrib"

projects[l10n_update][subdir] = "contrib"

projects[libraries][subdir] = "contrib"

projects[link][subdir] = "contrib"

projects[linkit][subdir] = "contrib"

projects[media][subdir] = "contrib"

projects[media_youtube][subdir] = "contrib"

projects[menu_block][subdir] = "contrib"

projects[menu_position][subdir] = "contrib"

projects[multiform][subdir] = "contrib"

projects[references][subdir] = "contrib"

projects[pathauto][subdir] = "contrib"

projects[plupload][subdir] = "contrib"

projects[rules][subdir] = "contrib"

projects[scheduler][subdir] = "contrib"

projects[search_log][subdir] = "contrib"

projects[skinr][subdir] = "contrib"

projects[special_menu_items][subdir] = "contrib"

projects[strongarm][subdir] = "contrib"

projects[token][subdir] = "contrib"

projects[transliteration][subdir] = "contrib"

projects[variable][subdir] = "contrib"

projects[varnish][subdir] = "contrib"

projects[views][subdir] = "contrib"

projects[views_php][subdir] = "contrib"

projects[webform][subdir] = "contrib"

projects[workbench][subdir] = "contrib"

projects[workbench_access][subdir] = "contrib"

projects[workbench_media][subdir] = "contrib"

; Libraries
libraries[plupload][download][type] = "get"
libraries[plupload][download][url] = "https://github.com/moxiecode/plupload/archive/v2.1.2.zip"
libraries[plupload][directory_name] = "plupload"
libraries[plupload][type] = "library"

libraries[htmlpurifier][download][type] = "get"
libraries[htmlpurifier][download][url] = "http://htmlpurifier.org/releases/htmlpurifier-4.5.0.tar.gz"
libraries[htmlpurifier][directory_name] = "htmlpurifier"
libraries[htmlpurifier][destination] = "libraries"

libraries[ckeditor][download][type]= "get"
libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor/CKEditor/CKEditor%203.6.2/ckeditor_3.6.2.zip"
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][destination] = "libraries"

libraries[jcarousel][download][type] = "get"
libraries[jcarousel][download][url] = "http://sorgalla.com/projects/download-zip.php?jcarousel"
libraries[jcarousel][directory_name] = "jquery.jcarousel"
libraries[jcarousel][destination] = "libraries"

libraries[jcycle][download][type] = "get"
libraries[jcycle][download][url] = "http://malsup.github.com/jquery.cycle.all.js"
libraries[jcycle][directory_name] = "jquery.cycle"
libraries[jcycle][destination] = "libraries"

libraries[solr-php-client][download][type] = "get"
libraries[solr-php-client][download][url] = "http://solr-php-client.googlecode.com/files/SolrPhpClient.r60.2011-05-04.zip"
libraries[solr-php-client][directory_name] = "SolrPhpClient"
libraries[solr-php-client][destination] = "libraries"
